kind: pipeline
name: migrator

workspace:
  base: /go
  path: src/github.com/lopezator/migrator

steps:
  - name: prepare
    image: golang:1.12.5
    commands:
      - make prepare

  - name: sanity-check
    image: golang:1.12.5
    commands:
      - make sanity-check

  - name: test
    image: golang:1.12.5
    environment:
      GO111MODULE: on
      GOPROXY: https://athens.azurefd.net
      POSTGRES_URL: postgres://postgres@postgres:5432/migrator?sslmode=disable
      MYSQL_URL: root:mysql@tcp(mysql:3306)/migrator
    commands:
      - sleep 30
      - make test

  - name: coverage
    image: plugins/codecov
    settings:
      files:
        - ./coverage.txt
    environment:
      CODECOV_TOKEN:
        from_secret: codecov_token

services:
  - name: postgres
    image: postgres:11.2
    ports:
      - 5432
    environment:
      POSTGRES_DB: migrator

  - name: mysql
    image: mysql:8.0.15
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: migrator
      MYSQL_ROOT_PASSWORD: mysql
